### PR TITLE
Set the NPCs X and Y position before invoking the NPC Spawn Hook

### PR DESCRIPTION
**Pull request by GitFlip**
I moved the setting of the NPCs X and Y position to before we invoke the NPC spawn hook. This will ensure that when you use the hook in a tShock plugin that the NPCs position will be set. This addresses this issue: https://github.com/Deathmax/TerrariaAPI-Server/issues/47

### CODE REVIEW

**Comment by Olink** [comment]
This commit is full of custom items and what not, how would we ever be able to accept this?

**Comment by Ijwu** [comment]
You need to be careful with pushing to branches in which there is an open PR. All of the changes will be reflected into the pull request and then we get a bunch of stuff that's out of scope and unusable to us.

If you make a pull request ensure that it's in its own branch and that you do not push more commits to the branch after making the pull request *unless the commits relate directly to the PR.*

**Comment by nicatronTg** [comment]
If we still want this code, I'd be happy to cherry pick it.

**Comment by GitFlip** [comment]
Sorry guys! I definitely must have accidentally did this back in November when I was trying to fix a problem we got in our own branch. I surely did not mean for any of this code to get up to the PR since it is custom code (as @Olink has mentioned) for our mod.

In the end I am not sure how I did that, so I'll be more careful. You can see that we've been at work in our own branch for quite some time now: https://github.com/GitFlip/TerrariaAPI-Server and I haven't accidentally done this again, so yeah... I'll just try to be more careful.

**Comment by nicatronTg** [comment]
You're pushing to master @GitFlip; the way open PRs work is that you add more "code" when ever you push to the PR'd branch.

If you want to do a PR in the future, cut a branch off of general-devel and use that only for your patch.

**Comment by GitFlip** [comment]
Okay, that makes sense. So I guess is it possible to take my current repo (the link above) and create my own branch that my friend and I can work off of?

**Comment by Olink** [comment]
You dont have to do anything because this pull request is closed.  If you ever want to submit a PR to this repo, you need to start over in a clean repo because your current codebase is so far ahead of ours.  You'd have to consult a git guru to fix your current repo

**Pull request closed without merging**
